version: "3.0"

services:
  start:
    container_name: virtual-jupyterlab-machine
    build:
      context: .
      dockerfile: build.dockerfile
    volumes:
      - .:/src
      - ~/.git-credentials:/root/.creds/.git-credentials
      - ~/.aws:/root/.aws
    environment:
      AWS_PROFILE: ${AWS_PROFILE}
      AWS_REGION: ${AWS_REGION}
      DEEPLAB_BUCKETNAME: deeplab-fileshareing
      PROJECT_NAME: DeepLab
    entrypoint: /entrypoint/scripts/start.sh
    tmpfs:
      - /root/.jupyter
      - /dataset
    privileged: true
    ports:
      - 5515:5515
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ "gpu" ]
