version: "3.0"
services:
  check_version:
    build:
      context: .
      dockerfile: build.dockerfile
    volumes:
      - .:/src
    command: /src/scripts/check_version.sh
  start:
    build:
      context: .
      dockerfile: build.dockerfile
    volumes:
      - .:/src
    entrypoint: /src/scripts/start.sh