version: "3.0"

services:
  start:
    container_name: virtual-jupyterlab-machine
    build:
      context: .
      dockerfile: build.dockerfile
    volumes:
      - .:/src
      - ~/.git-credentials:/root/.creds/.git-credentials:ro
      - ~/.aws:/root/.aws:ro
    environment:
      AWS_PROFILE: ${AWS_PROFILE}
      AWS_REGION: ${AWS_REGION}
      DEEPLAB_BUCKETNAME: deeplab-fileshareing
      PROJECT_NAME: DeepLab
    entrypoint: /entrypoint/scripts/start.sh
    tmpfs:
      - /root/.jupyter
      - /dataset
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ "gpu" ]
    ports:
      - 3443:5515
#   https:
#     image: steveltn/https-portal:1
#     ports:
#       - 3443:443
#     environment:
#       STAGE: local
#       DOMAINS: 'localhost.com -> http://start:5515'
#     links:
#       - start
#     volumes:
#       - https-portal-data:/var/lib/https-portal
#       - /var/run/docker.sock:/var/run/docker.sock:ro
# volumes:
#   https-portal-data:
