version: "3.0"


services:
  check_version:
    container_name: check-version-deeplab
    build:
      context: .
      dockerfile: build.dockerfile
    volumes:
      - .:/src
    command: /src/scripts/check_version.sh
  deploy:
    container_name: deploying-aws-resources
    build:
      context: .
      dockerfile: build.dockerfile
    volumes:
      - .:/src
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      DEPLOY_STACKNAME: DeepLab
      DEPLOY_PROJECTNAME: DeepLab
      DEEPLAB_BUCKETNAME: deeplab-fileshareing
    entrypoint: /src/scripts/deploy.sh
