version: "3.0"


services:
  check_version:
    build:
      context: .
      dockerfile: build.dockerfile
    volumes:
      - .:/src
    command: /src/scripts/check_version.sh
  deploy:
    build:
      context: .
      dockerfile: build.dockerfile
    volumes:
      - .:/src
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      DEPLOY_STACKNAME: DeepLab
      DEEPLAB_BUCKETNAME: deeplab-fileshareing
    entrypoint: /src/scripts/deploy.sh
  start:
    build:
      context: .
      dockerfile: build.dockerfile
    volumes:
      - .:/src
      - ~/.aws:/root/.aws
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      DEEPLAB_BUCKETNAME: deeplab-fileshareing
      GIT_CREDENTIALS: ${GIT_CREDENTIALS}
      GIT_USERNAME: ${GIT_USERNAME}
      GIT_USERMAIL: ${GIT_USERMAIL}
    entrypoint: /src/scripts/start.sh
    tmpfs:
      - /root/.jupyter
      - /dataset
    privileged: true
    ports:
      - 5515:5515
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
