name: Push Container Image
on:
  push:
    branches:
      - main
      - stg

jobs:
  push:
    name: Push container image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          username: streamwest1629
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: streamwest1629/deeplab
          tags: |
            type=sha
            type=raw,value=latest
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: publish.dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
